name: Health check

on:
  schedule:
    - cron: '* * * * *' # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check that the app is working
        uses: jtalk/url-health-check-action@v2
        with:
          url: 'https://pokedex-pipeline-app.herokuapp.com/healthcheck'
          max-attempts: 3
          retry-delay: 5s
