name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run eslint

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm test

      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'pokedex-pipeline-app'
          heroku_email: 'kavanderjanne@gmail.com'
          healthcheck: 'https://pokedex-pipeline-app.herokuapp.com/healthcheck'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true

      - uses: actions/checkout@v2 # This solves crash when creating a tag
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' &&  (!contains(join(toJson(github.event.commits.*.message)), '#skip')) }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'patch'
